### ISSUE TITLE
Trying to Set next one time boot to virtual media device

### ISSUE THREAD

**Issue by rlopez133** [dell/iDRAC-Redfish-Scripting#116]
Hello,

I'm getting a weird issue with my iDRAC (2.70.70.70 , PowerEdge R730xd) where at times I get a 503 error and only after a racadm racreset does it work the initial first time and fails afterwards everytime with 503. I'm using the script as such:

Scrubbed creds. 
```
python3 ./SetNextOneTimeBootVirtualMediaDeviceOemREDFISH.py -ip 192.168.0.2 -u ADMIN -p PASSWORD -d 1 -r y
```

If I attempt after a successful run, I get:

```

- WARNING, setting next onetime boot device to Virtual CD

- FAIL: status code 503 returned
- Detailed error information: {'_content': b'', '_content_consumed': True, '_next': None, 'status_code': 503, 'headers': {'Strict-Transport-Security': 'max-age=63072000', 'Vary': 'Accept-Encoding', 'Content-Type': 'application/json; charset=utf-8', 'Server': 'iDRAC/8', 'Date': 'Wed, 24 Jun 2020 02:07:13 GMT', 'Cache-Control': 'no-cache', 'Connection': 'Keep-Alive', 'Transfer-Encoding': 'chunked', 'Accept-Ranges': 'bytes'}, 'raw': <urllib3.response.HTTPResponse object at 0x7fd46cde4080>, 'url': 'https://192.168.0.2/redfish/v1/Managers/iDRAC.Embedded.1/Actions/Oem/EID_674_Manager.ImportSystemConfiguration', 'encoding': 'utf-8', 'history': [], 'reason': 'Service Unavailable', 'cookies': <RequestsCookieJar[]>, 'elapsed': datetime.timedelta(0, 0, 600526), 'request': <PreparedRequest [POST]>, 'connection': <requests.adapters.HTTPAdapter object at 0x7fd46ce38860>}
```

Any ideas why this happens? I have nothing pending in my jobqueue

Another question I have is, I'd like to be able to do this as a Ansible task and I've attempted this with no luck. Is there something wrong with my body format?

```
- name: Set Boot Override to VirtualMedia
  uri:
    url: "https://192.168.0.2/redfish/v1/Managers/iDRAC.Embedded.1/Actions/Oem/EID_674_Manager.ImportSystemConfiguration"
    validate_certs: no
    method: POST
    user: "ADMIN"
    password: "PASSWORD"
    headers:
      content-type: application/json
    body: '{"ShareParameters":{"Target":"ALL"},"ImportBuffer":"<SystemConfiguration><Component FQDD=\"iDRAC.Embedded.1\"><Attribute Name=\"ServerBoot.1#BootOnce\">Enabled</Attribute><Attribute Name=\"ServerBoot.1#FirstBootDevice\">VCD-DVD</Attribute></Component></SystemConfiguration>"}'

```

**Comment by rlopez133** [comment]
@texroemer was wondering if by chance you had any sight? thanks a million :)

**Comment by texroemer** [comment]
Hi @rlopez133 

After a successful run of setting onetime boot to virtual CD, server reboots and boots to ISO, can you let me know what state the server is in when you try the onetime boot command again and fails? Is the server still booted to the ISO, server booted to the OS, server off, etc?

Also when in failed state, can you try a different POST action, see if it passes? This will help in figuring out if Redfish API itself is having issues or just a certain action is failing. You can use script SetPowerStateREDFISH.py to execute POST action to reboot the server.

Thanks

**Comment by rlopez133** [comment]
@texroemer so I went off and tried the following

* Reset my racadm
* Ran the .py 3 times in a row waiting for the boot to happen all worked
* Attempted the curl command and then manually rebooted twice and worked
* Add the curl command as a shell module in Ansible it worked
* Attempted Ansible using the uri module and fails with 503.

In a nutshell, my problem is my uri module :( I'm sadly not passing something correctly. Latest attempt

```
- name: Set Boot Override to VirtualMedia
  uri:
    url: "https://192.168.0.2/redfish/v1/Managers/iDRAC.Embedded.1/Actions/Oem/EID_674_Manager.ImportSystemConfiguration"
    validate_certs: no
    return_content: yes
    method: POST
    user: "ADMIN"
    password: "PASSWORD"
    headers:
      Content-Type: application/json
      Accept: application/json;odata.metadata=minimal;charset=utf-8
    body_format: json
    body: '{"ShareParameters":{"Target":"ALL"},"ImportBuffer":"<SystemConfiguration><Component FQDD=\"iDRAC.Embedded.1\"><Attribute Name=\"ServerBoot.1#BootOnce\">Enabled</Attribute><Attribute Name=\"ServerBoot.1#FirstBootDevice\">VCD-DVD</Attribute></Component></SystemConfiguration>"}'
```
Just curious if by chance you see something wrong here? i understand your not dealing with Ansible I'm just wondering if theres some header or something else I need to be passing that will give a clue

This curl works
```
curl -k -u ADMIN:PASSWORD -X POST https://192.168.0.2/redfish/v1/Managers/iDRAC.Embedded.1/Actions/Oem/EID_674_Manager.ImportSystemConfiguration -H "Content-Type: application/json" -d '{"ShareParameters":{"Target":"ALL"},"ImportBuffer":"<SystemConfiguration><Component FQDD=\"iDRAC.Embedded.1\"><Attribute Name=\"ServerBoot.1#BootOnce\">Enabled</Attribute><Attribute Name=\"ServerBoot.1#FirstBootDevice\">VCD-DVD</Attribute></Component></SystemConfiguration>"}'
```

Appreciate all your guidance, really helped troubleshoot. I guess when I was attempting the Ansible cmds it was putting it in 503 state and then the regular .py or curl commands when I'd run manually wouldn't work at that point.

**Comment by texroemer** [comment]
@rlopez133 

I've only used Ansible a few times but this was calling playbooks. How are you calling the uri module you created directly, can you give me an example and i'll try it out.

Thanks

**Comment by texroemer** [comment]
@rlopez133 

I was able to repro your issue on iDRAC 8, issue does not occur on iDRAC 9 using same playbook. I went ahead and escalated this issue to the Redfish team at Dell, will let you know once i hear back.

Thanks

**Comment by rlopez133** [comment]
Hi @texroemer , 

my observations:
* With iDRAC8, the below shell module curl doesn't work.
* With iDRAC9, the below shell module curl works.
* uri module fails both iDRAC versions (likely Ansible bug)
* I wish redfish_command Ansible module had the ability to boot into Virtual CD

Regarding the URI module, this is something I tried but doesn't work and I believe it may be an Ansible bug. 

For example, I've gone and reverted to using shell directly in Ansible, something like

```
    - name: Set BootOnce into Virtual CD (DELL)
      shell: |
             curl -k -u {{ user }}:{{ password }} -X POST https://{{ bmc_address }}/redfish/v1/Managers/iDRAC.Embedded.1/Actions/Oem/EID_674_Manager.ImportSystemConfiguration -H "Content-Type: application/json" -d '{"ShareParameters":{"Target":"ALL"},"ImportBuffer":"<SystemConfiguration><Component FQDD=\"iDRAC.Embedded.1\"><Attribute Name=\"ServerBoot.1#BootOnce\">Enabled</Attribute><Attribute Name=\"ServerBoot.1#FirstBootDevice\">VCD-DVD</Attribute></Component></SystemConfiguration>"}' -i

```

Ideally, there would be a module in https://docs.ansible.com/ansible/latest/modules/redfish_command_module.html that would let you boot into VirtualMedia.

However, if that is not available (redfish_command module), I'd expect something like this to work using the URI module

```
- name: Set Boot Override to VirtualMedia
  uri:
    url: "https://{{ bmc_address 
 }}/redfish/v1/Managers/iDRAC.Embedded.1/Actions/Oem/EID_674_Manager.ImportSystemConfiguration"
    validate_certs: no
    method: POST
    user: "{{ user }}"
    password: "{{ password }}"
    headers:
      content-type: application/json
      accept: application/json
    body_format: json
    body: "{{ lookup('file','body.json') }}"
```

The body.json file
```
{
  "ShareParameters": {
    "Target": "ALL"
  },
  "ImportBuffer": "<SystemConfiguration><Component FQDD=\"iDRAC.Embedded.1\"><Attribute Name=\"ServerBoot.1#BootOnce\">Enabled<\/Attribute><Attribute Name=\"ServerBoot.1#FirstBootDevice\">VCD-DVD<\/Attribute><\/Component><\/SystemConfiguration>"
}
```

However, that URI request doesn't work as it complains about body format. This is easier to see if you attempted something like the below where your just trying to boot up the server. For example

```
- name: Power on System
  uri:
    url: "https://{{ bmc_address 
 }}/redfish/v1/Systems/System.Embedded.1/Actions/ComputerSystem.Reset"
    validate_certs: no
    method: POST
    user: "{{ user }}"
    password: "{{ password }}"
    headers:
      content-type: application/json
      accept: application/json
    body_format: json
    body: "{'ResetType': 'On'}"
```
```

**Comment by texroemer** [comment]
@rlopez133 

Your URI module is not configured correctly. See my example below where its passing for me on iDRAC 9 (iDRAC 8 still fails which i'm still working with Redfish team on this issue).

[root@localhost dellemc-openmanage-ansible-modules]# ansible-playbook scp_local.yml -i inventory_14g.yml

PLAY [myhosts] ***************************************************************************

TASK [set onetime virtual CD using SCP] **************************************************
ok: [redfish1]

PLAY RECAP *******************************************************************************
redfish1                   : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

[root@localhost dellemc-openmanage-ansible-modules]# cat scp_local.yml
---
- hosts: myhosts
  connection: local
  gather_facts: False
  tasks:
  - name: set onetime virtual CD using SCP
    uri:
      url: "https://{{ ip }}/redfish/v1/Managers/iDRAC.Embedded.1/Actions/Oem/EID_674_Manager.ImportSystemConfiguration"
      user: "{{ username }}"
      password: "{{ password }}"
      method: POST
      headers:
        content-type: application/json
        Accept: application/json
      body: {"ShareParameters":{"Target":"ALL"},"ImportBuffer":"<SystemConfiguration><Component FQDD=\"iDRAC.Embedded.1\"><Attribute Name=\"ServerBoot.1#BootOnce\">Enabled</Attribute><Attribute Name=\"ServerBoot.1#FirstBootDevice\">VCD-DVD</Attribute></Component></SystemConfiguration>"}
      body_format: json
      validate_certs: no
      status_code: 202
      return_content: yes

**Comment by rlopez133** [comment]
@texroemer on a FC640 that I have access to 

```
    - name: set onetime virtual CD using SCP
      uri:
        url: "https://{{ hostvars[item]['bmc_address'] }}/redfish/v1/Managers/iDRAC.Embedded.1/Actions/Oem/EID_674_Manager.ImportSystemConfiguration"
        user: "{{ hostvars[item]['bmc_user'] }}"
        password: "{{ hostvars[item]['bmc_password'] }}"
        method: POST
        headers:
          content-type: application/json
          Accept: application/json
        body: '{"ShareParameters":{"Target":"ALL"},"ImportBuffer":"<Component FQDD="iDRAC.Embedded.1"><Attribute Name="ServerBoot.1#BootOnce">Enabled<Attribute Name="ServerBoot.1#FirstBootDevice">VCD-DVD"}'
        body_format: json
        validate_certs: no
        status_code: 202
        return_content: yes

```

It's not happy :/ 

```
[FAILED! => {"access_control_allow_origin": "*", "cache_control": "no-cache", "changed": false, "connection": "close", "content": "{\"error\":{\"@Message.ExtendedInfo\":[{\"Message\":\"Unable to complete the operation because the JSON data format entered is invalid.\",\"MessageArgs\":[],\"MessageArgs@odata.count\":0,\"MessageId\":\"IDRAC.2.1.SYS405\",\"RelatedProperties\":[],\"RelatedProperties@odata.count\":0,\"Resolution\":\"Do the following and the retry the operation: 1) Enter the correct JSON data format and retry the operation. 2) Make sure that no syntax error is present in JSON data format. 3) Make sure that a duplicate key is not present in JSON data format.\",\"Severity\":\"Critical\"},{\"Message\":\"The request body submitted was malformed JSON and could not be parsed by the receiving service.\",\"MessageArgs\":[],\"MessageArgs@odata.count\":0,\"MessageId\":\"Base.1.5.MalformedJSON\",\"RelatedProperties\":[],\"RelatedProperties@odata.count\":0,\"Resolution\":\"Ensure that the request body is valid JSON and resubmit the request.\",\"Severity\":\"Critical\"}],\"code\":\"Base.1.5.GeneralError\",\"message\":\"A general error has occurred. See ExtendedInfo for more information\"}}\n", "content_length": "1015", "content_type": "application/json;odata.metadata=minimal;charset=utf-8", "date": "Mon, 29 Jun 2020 21:38:25 GMT", "elapsed": 0, "json": {"error": {"@Message.ExtendedInfo": [{"Message": "Unable to complete the operation because the JSON data format entered is invalid.", "MessageArgs": [], "MessageArgs@odata.count": 0, "MessageId": "IDRAC.2.1.SYS405", "RelatedProperties": [], "RelatedProperties@odata.count": 0, "Resolution": "Do the following and the retry the operation: 1) Enter the correct JSON data format and retry the operation. 2) Make sure that no syntax error is present in JSON data format. 3) Make sure that a duplicate key is not present in JSON data format.", "Severity": "Critical"}, {"Message": "The request body submitted was malformed JSON and could not be parsed by the receiving service.", "MessageArgs": [], "MessageArgs@odata.count": 0, "MessageId": "Base.1.5.MalformedJSON", "RelatedProperties": [], "RelatedProperties@odata.count": 0, "Resolution": "Ensure that the request body is valid JSON and resubmit the request.", "Severity": "Critical"}], "code": "Base.1.5.GeneralError", "message": "A general error has occurred. See ExtendedInfo for more information"}}, "msg": "Status code was 400 and not [202]: HTTP Error 400: Bad Request", "odata_version": "4.0", "redirected": false, "server": "Apache", "status": 400, "strict_transport_security": "max-age=63072000; includeSubDomains; preload", "url": "https://mgmt-e20-h14-b03-fc640.rdu2.scalelab.redhat.com/redfish/v1/Managers/iDRAC.Embedded.1/Actions/Oem/EID_674_Manager.ImportSystemConfiguration", "x_frame_options": "DENY"}

```
