### ISSUE TITLE
Redfish API error "msg": "Status code was 405 and not [200]: HTTP Error 405: Method Not Allowed",

### ISSUE THREAD

**Issue by ashokbeh** [dell/iDRAC-Redfish-Scripting#194]
Hi,
Using Ansible playbook trying to run a diagnostic test against the Dell poweredge server using iDRAC.
However,on POST to initiate the diagnostic, encountered an error

 "msg": "Status code was 405 and not [200]: HTTP Error 405: Method Not Allowed",
    "odata_version": "4.0",
    "redirected": false,
    "server": "Apache",
    "status": 405,
    "strict_transport_security": "max-age=63072000; includeSubDomains; preload",
    "url": "https://xxx.corp/redfish/v1/Managers/iDRAC.Embedded.1/DellLCService/Actions/DellLCService.RunePSADiagnostics",
    "x_frame_options": "DENY"

If we use curl to test the Redfish API it does not through the error.

curl -k -u "XXXX:XXXX" -v -H "Content-Type: application/json" -d "{\"RebootJobType\": \"GracefulRebootWithoutForcedShutdown\", \"RunMode\": \"Express\"}" https://xxxx.corp/redfish/v1/Managers/iDRAC.Embedded.1/Oem/Dell/DellLCService/Actions/DellLCService.RunePSADiagnostics
*   Trying x.x.x.x...
* TCP_NODELAY set
* Connected to xxxx.corp (xx.xx.xx.xx) port 443 (#0)
* schannel: SSL/TLS connection with xxxx.corp port 443 (step 1/3)
* schannel: disabled server certificate revocation checks
* schannel: verifyhost setting prevents Schannel from comparing the supplied target name with the subject names in server certificates. Also disables SNI.
* schannel: sending initial handshake data: sending 168 bytes...
* schannel: sent initial handshake data: sent 168 bytes
* schannel: SSL/TLS connection with xxxx.corp port 443 (step 2/3)

{"@Message.ExtendedInfo":[{"Message":"The operation successfully completed.","MessageArgs":[],MessageArgs@odata.count:0,"MessageId":"IDRAC.2.4.SYS413","RelatedProperties":[],RelatedProperties@odata.count:0,"Resolution":"No response action is required.","Severity":"Informational"},{"Message":"Successfully Completed Request","MessageArgs":[],MessageArgs@odata.count:0,"MessageId":"Base.1.7.Success","RelatedProperties":[],RelatedProperties@odata.count:0,"Resolution":"None","Severity":"OK"}]}* Curl_http_done: called premature == 0
* Connection #0 to host xxxx.corp left intact

iDRAC version: 5.00.10.20
iDRAC 9  servergen 14G

Would appreciate if anyone can help.

**Comment by texroemer** [comment]
Hi @ashokbeh 

Since this is an Ansible issue, can you please post this on Dell Ansible GitHub page:

https://github.com/dell/redfish-ansible-module/issues

Thanks
Tex

**Comment by anupamaloke** [comment]
@ashokbeh, I guess you are not using the correct URL in the playbook:
> "url": "https://xxx.corp/redfish/v1/Managers/iDRAC.Embedded.1/DellLCService/Actions/DellLCService.RunePSADiagnostics",

You need to use https://xxx.corp/redfish/v1/Managers/iDRAC.Embedded.1/Oem/Dell/DellLCService/Actions/DellLCService.RunePSADiagnostics.

I was able to run the following playbook successfully:
```
  tasks:
  - name: run diagnostics
    ansible.builtin.uri:
      url: "https://{{ inventory_hostname }}/redfish/v1/Managers/iDRAC.Embedded.1/Oem/Dell/DellLCService/Actions/DellLCService.RunePSADiagnostics"
      user: "{{ user }}"
      password: "{{ password }}"
      validate_certs: False
      force_basic_auth: yes
      method: POST
      headers:
        Accept: "application/json"
        Content-Type: "application/json"
        OData-Version: "4.0"
      body:
        RebootJobType: "GracefulRebootWithoutForcedShutdown"
        RunMode: "Express"
      body_format: json
      status_code: [200, 202]
    register: result
```
