### ISSUE TITLE
Job history of iDRAC using Redfish

### ISSUE THREAD

**Issue by ashokbeh** [dell/iDRAC-Redfish-Scripting#200]
Hi,
I am in need of a Redfish API that can validate if a particular job is run most recently in iDRAC 9.

For example:
Remote diagnostic.
Scheduled tart time:
Scheduled end time.

Can we use the redfish URL ?
URL
/redfish/v1/Managers//Jobs/<Job-Id
But we cannot use the job-id because that will vary unlike job name "Remote Diagnostics".
As part of the script we need to collect the such job and its id

Example from a iDRAC 9 GUI

                              ID                                                       Job                                                                               Status
                RID_414099047932          Reboot: Graceful OS shutdown with powercycle on timeout         Reboot Completed (100%)
                JID_414099044945           Remote Diagnostics        Completed (100%)
                           Scheduled Start Time2022-01-05T19:11:44
                           Actual Start Time2022-01-05T19:17:24
                           Expiration TimeNot Applicable
                           Actual Completion Time2022-01-05T21:18:11
                           MessageSYS018: Job completed successfully.

Would appreciate your support to advise the most suitable Redfish URL for iDRAC9.

Regards
Ashok Behera

**Comment by anupamaloke** [comment]
@ashokbeh, I am guessing following is the workflow that you are looking to automate using ansible:

- Find out whether there are any Remote Diagnostics jobs are running.
- If yes, then monitor the existing job till completion or failure
- If not, then create a new remote diagnostics job and monitor the job till completion or failure.
An ansible-role ```idrac_diagnostics``` would be the best for realizing the above workflow. In the meanwhile, following is a sample playbook:

```
  tasks:
  - name: Get the job queue
    ansible.builtin.uri:
      url: "https://{{ inventory_hostname }}/redfish/v1/Managers/iDRAC.Embedded.1/Oem/Dell/Jobs?$expand=*"
      user: "root"
      password: "Dell_123"
      validate_certs: False
      force_basic_auth: yes
      method: GET
      headers:
        Accept: "application/json"
        OData-Version: "4.0"
      status_code: 200
    register: job_queue_response

  - name: check if a diagnostics job is still running
    ansible.builtin.set_fact:
      diag_jobs: "{{ job_queue_response.json.Members | selectattr('Name', 'eq', 'Remote Diagnostics') }}"
    when:
      - job_queue_response.json["Members@odata.count"] > 0

  - ansible.builtin.debug:
      var: diag_jobs

  - block:
      - name: get the diag job ID if still running
        ansible.builtin.set_fact:
          diag_job_id: "{{ item.Id }}"
          diag_job_running: True
        when:
          - item.JobState == "Running"
        loop: "{{ diag_jobs }}"
    when:
      - diag_jobs is defined and diag_jobs|length > 0

  - ansible.builtin.debug:
      msg: "{{ diag_job_id }} {{ diag_job_running }}"
    when:
      - diag_job_id is defined and diag_job_running is defined

  - block:
      - name: run diagnostics
        ansible.builtin.uri:
          url: "https://{{ inventory_hostname }}/redfish/v1/Managers/iDRAC.Embedded.1/Oem/Dell/DellLCService/Actions/DellLCService.RunePSADiagnostics"
          user: "root"
          password: "Dell_123"
          validate_certs: False
          force_basic_auth: yes
          method: POST
          headers:
            Accept: "application/json"
            Content-Type: "application/json"
            OData-Version: "4.0"
          body:
            RebootJobType: "GracefulRebootWithoutForcedShutdown"
            RunMode: "Express"
          body_format: json
          status_code: [200, 202]
        register: diag_response

      - name: get the job ID
        ansible.builtin.set_fact:
          diag_job_id: "{{ diag_response.location.split('/')[-1] }}"

    when:
      - (diag_job_running is not defined) or (not diag_job_running)

  - name: track job till completion
    dellemc.openmanage.idrac_lifecycle_controller_job_status_info:
      idrac_ip: "{{ inventory_hostname }}"
      idrac_user: "{{ user }}"
      idrac_password: "{{ password }}"
      job_id: "{{ diag_job_id }}"
    register: result
    until: result.job_info.JobStatus == "Completed" or result.job_info.JobStatus == "Failed"
    failed_when: result.job_info.JobStatus == "Failed"
    retries: 6
    delay: 300
    when:
      - diag_job_id

```
